# Generated by Django 5.0.dev20230312155420 on 2023-04-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippoingAddress',
            new_name='ShippingAddress',
        ),
    ]
